name: Workflow Name

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  GH_BRANCH_BASE: ${{ github.event.pull_request.base.ref }}
  GH_BRANCH: ${{ github.event.pull_request.head.ref }}
  GH_BRANCH_SHA: ${{ github.event.pull_request.head.sha }}

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ env.GITHUB_TOKEN }}
          fetch-depth: 0
          ref: ${{ env.GH_BRANCH }}

      - run: |
          git config user.name github-actions
          git config user.email github-actions[bot]@users.noreply.github.com

          if git merge-base --is-ancestor ${{ env.GH_BRANCH_BASE }} ${{ env.GH_BRANCH_SHA }};
            then
              echo "This branch is up to date with main";
              exit 1;
          fi

          git fetch origin ${{ env.GH_BRANCH_BASE }}
          git pull --rebase origin ${{ env.GH_BRANCH_BASE }}

          git push origin ${{ env.GH_BRANCH }} --force-with-lease
