name: Workflow Name

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ env.GITHUB_TOKEN }}
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - run: |
          git config user.name github-actions
          git config user.email github-actions[bot]@users.noreply.github.com

          git fetch --all

          BASE_SHA=$(git rev-parse ${{ github.event.pull_request.base.ref }})
          HEAD_SHA=$(git rev-parse ${{ github.head_ref }})

          if [ "$BASE_SHA" == "$HEAD_SHA" ]; then
            echo "Branch is not up-to-date with base branch. Please update your branch."
            exit 0
          fi

          echo "Rebasing from ${{ github.event.pull_request.base.ref }}"

          git fetch origin ${{ github.event.pull_request.base.ref }}
          git pull --rebase origin ${{ github.event.pull_request.base.ref }}

          git push origin ${{ github.head_ref }} --force-with-lease
