name: Workflow Name

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ env.GITHUB_TOKEN }}
          fetch-depth: 0

      - uses: cirrus-actions/rebase@1.8
