name: Workflow Name

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
  issue_comment:
    types:
      - created
      - edited

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  GH_BRANCH_BASE: ${{ github.event.pull_request.base.ref }}
  GH_BRANCH: ${{ github.event.pull_request.head.ref }}
  GH_BRANCH_SHA: ${{ github.event.pull_request.head.sha }}
  GH_BOT_NAME: github-actions
  GH_BOT_EMAIL: github-actions[bot]@users.noreply.github.com

jobs:
  rebase:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' || (github.event_name == 'issue_comment' && contains(github.event.comment.html_url, '/rebase')) }}
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ env.GITHUB_TOKEN }}
          fetch-depth: 0
          ref: ${{ env.GH_BRANCH }}

      - id: branch_status
        name: Check if branch is up-to-date
        run: |
          if git merge-base --is-ancestor ${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.head.sha }};
          then
            echo "up_to_date=true" >> $GITHUB_OUTPUT
          else
            echo "up_to_date=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Try to rebase
        id: branch_rebase
        if: ${{ steps.branch_status.outputs.up_to_date == 'false' }}
        run: |
          git config user.name $(git log -1 --pretty=format:'%an')
          git config user.email $(git log -1 --pretty=format:'%ae')

          git fetch origin ${{ env.GH_BRANCH_BASE }}
          git pull --rebase origin ${{ env.GH_BRANCH_BASE }}

          git push origin ${{ env.GH_BRANCH }} --force-with-lease

          echo "success=true" >> $GITHUB_OUTPUT

      - name: Comment on pull request
        if: ${{ steps.branch_status.outputs.up_to_date == 'true' || steps.branch_rebase.outputs.success == 'true' }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            OMG ta funcionando
          pr_number: ${{ github.event.pull_request.number }}
          comment_tag: to_delete
          mode: delete
