name: Workflow Name

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ env.GITHUB_TOKEN }}
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - run: |
          git config user.name github-actions
          git config user.email github-actions[bot]@users.noreply.github.com

          if git merge-base --is-ancestor ${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.head.sha }};
            then
              echo "This branch is up to date with main";
              exit 1;
          fi

          git fetch origin ${{ github.event.pull_request.base.ref }}
          git pull --rebase origin ${{ github.event.pull_request.base.ref }}

          git push origin ${{ github.head_ref }} --force-with-lease
