name: Workflow Name

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  GH_PR_BRANCH_BASE: ${{ github.event.pull_request.base.ref }}

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ env.GITHUB_TOKEN }}
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - run: |
          git config user.name github-actions
          git config user.email github-actions[bot]@users.noreply.github.com

          git fetch origin ${{ env.GH_PR_BRANCH_BASE }}
          git pull --rebase origin ${{ env.GH_PR_BRANCH_BASE }}

          git push origin ${{ github.head_ref }} --force
