name: Workflow Name

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
  issue_comment:
    types:
      - created
      - edited

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  GH_BRANCH_BASE: ${{ github.event.pull_request.base.ref }}
  GH_BRANCH: ${{ github.event.pull_request.head.ref }}
  GH_BRANCH_SHA: ${{ github.event.pull_request.head.sha }}
  GH_BOT_NAME: github-actions
  GH_BOT_EMAIL: github-actions[bot]@users.noreply.github.com

jobs:
  rebase:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'github-actions' || (github.event_name == 'issue_comment' && contains(github.event.comment.html_url, '/rebase') || github.event_name == 'pull_request') }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ env.GITHUB_TOKEN }}
          fetch-depth: 0
          ref: ${{ env.GH_BRANCH }}

      - id: rebase_status
        run: |
          git config user.name ${{ env.GH_BOT_NAME }}
          git config user.email ${{ env.GH_BOT_EMAIL }}

          if git merge-base --is-ancestor ${{ env.GH_BRANCH_BASE }} ${{ env.GH_BRANCH_SHA }};
            then
              exit 1;
          fi

          git fetch origin ${{ env.GH_BRANCH_BASE }}
          git pull --rebase origin ${{ env.GH_BRANCH_BASE }}

          git push origin ${{ env.GH_BRANCH }} --force-with-lease

          echo "::set-output name=success::true"

  comment:
    needs: rebase
    if: success()
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            TA REBASED 👻
          pr_number: ${{ github.event.pull_request.number }}
          mode: delete
